Add Tests and TravisCI integration
appsembler/tahoe_cert_agent pull request #1
Opened 2018-08-24 15:52 UTC by thraxil

just a dummy test to get started with.

2018-08-27 18:07 UTC, bezidejni commented
@thraxil I see that you're still adding commits, just let me know when it's ready to be reviewed and I'll hop right on it.

2018-08-28 08:19 UTC, thraxil commented
@bezidejni review it any time you want.

2018-08-28 17:30 UTC, bezidejni requested changes
Just a small change, otherwise looks good.

2018-08-28 17:30 UTC, bezidejni commented on Makefile
> +	virtualenv .test-ve
It might be good to specify the exact major version of python so we don't end up using Python 3.

2018-09-17 15:37 UTC, thraxil commented
Still waiting on this one.

2018-09-18 08:58 UTC, bezidejni commented
@thraxil Sorry about it, I didn't see that you made a change and I forgot about this PR.

2018-09-18 08:58 UTC, bezidejni approved these changes

2018-09-18 10:16 UTC, merged